### ISSUE TITLE
Repeated flags?

### ISSUE THREAD

**Issue by gleachkr** [leanprover/lean4-cli#18]
It would be nice to be able to handle repeated flags, as in `readelf -x 1 -x 2 /bin/true` or something similar. It seems like that's not possible right now, is that right?

**Comment by mhuisi** [comment]
You can't have repeated flags, but you can make `x` an `Array` and then call it with `-x 1,2`.

**Comment by mhuisi** [comment]
@gleachkr Is this sufficient for your use case?

**Comment by gleachkr** [comment]
Yes, that will work for my case (though repeated flags might be nice-to-have in general). Thanks for this excellent library!
